FROM php:8.2-apache

#cài đặt các extent php cần thiết
RUN docker-php-ext-install pdo pdo_mysql

#cài đặt các toll bổ sung
RUN apt-get update && apt-get install -y \
    git \
    zip \
    unzip \
    vim \
    ca-certificates \
    && update-ca-certificates

#Enable Apache mod_rewrite (nếu cần)
RUN a2enmod rewrite

#copy code vào container
COPY . /var/www/html/

#set quyền truy cập
RUN chown -R www-data:www-data /var/www/html \
    && chmod -R 755 /var/www/html

#Expose part
EXPOSE 80

#Start Apache 
CMD [ "apache2-foreground" ]
